apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-prod
  namespace: frontend-dev
spec:
  selector:
    matchLabels:
      type: web
  replicas: 1
  template:
    metadata:
      labels:
        type: web
  spec:
    containers:
    - name: container
      image: songhyeon/front:latest
      envFrom:
      - configMapRef:
          name: httpd-cm-prod
      ports:
      - containerPort: 80