apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: msh-dev
spec:
  selector:
    matchLabels:
      type: front
  replicas: 1
  template:
    metadata:
      labels:
        type: front
    spec:
      containers:
      - name: container
        image: songhyeon/front:latest
        ports:
        - containerPort: 80